set(HWC_BOUNDARY "{0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9}")
set(BTB_IGNORE_ALL_HOT "false")
set(BTB_SORT_HIT_ACCESS "false")
set(BTB_USE_LRU "true")
set(BTB_CONSIDER_WARM_TAKEN "false")
set(BTB_CONSIDER_HOT_TAKEN "false")
set(BTB_CONSIDER_KEEP "true")
set(BTB_CONSIDER_TAKEN_HISTORY "false")
set(BTB_CURR_HOTTER "true")
