set(
        MODULES
        prefetcher_fdip_l1i
        prefetcher_no_l1d
        prefetcher_no_l2c
        prefetcher_no_llc
        replacement_lru_llc
        branch_tage-sc-l
        btb-generated_hwc_btb_set_8_cate_f_keep_curr_hotter_lru
)
