set(
        MODULES
        prefetcher_next_line_l1i
        prefetcher_no_l1d
        prefetcher_no_l2c
        prefetcher_no_llc
        replacement_lru_llc
        branch_tage-sc-l
        btb_basic_btb
)